### ISSUE TITLE
Ticketing System In Django

### ISSUE THREAD

**Issue by Ladet02** [dearkafka/woot#1]
Please give me an Idea of how I can utilize this wrapper to build a ticketing system for my users in python Django

**Comment by dearkafka** [comment]
@Ladet02 wrapper allows easily access all chatwoot API. E.g. you can create a API channel https://www.chatwoot.com/docs/product/channels/api/create-channel/ which can send all events to specified webhook. so you would need to code server for that webhook that would process all messages and do what you want with them (ticketing system). I also have a very simple webhook server (its not for API Channel though but API Channel is similar, see chatwoot api docs) so you would get the idea of how it works https://github.com/dearkafka/woothook/
